# Generated by Django 2.0.7 on 2019-10-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='podsumowanie',
            field=models.TextField(default='Django to najlepszy framework'),
        ),
    ]
