# Generated by Django 2.2.5 on 2019-10-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_produkt_podsumowanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
