# Generated by Django 2.2.5 on 2019-10-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0003_auto_20191012_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='przecena',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
