# Generated by Django 2.2.5 on 2019-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0004_produkt_przecena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='przecena',
            field=models.BooleanField(default=False),
        ),
    ]
